# STOR 120 -  Lab 3: Arrays, Tables, & Visualizations

Welcome to Lab 3!



First run the cell below.

In [279]:
# Just run this cell

import numpy as np
from datascience import *

# These lines do some fancy plotting magic
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# 1. Arrays

Computers are most useful when you can use a small amount of code to *do the same action* to *many different things*.

For example, in the time it takes you to calculate the 18% tip on a restaurant bill, a laptop can calculate 18% tips for every restaurant bill paid by every human on Earth that day (That's if you're pretty fast at doing arithmetic in your head!).

**Arrays** are how we put many values in one place so that we can operate on them as a group. For example, if `billions_of_numbers` is an array of numbers, the expression

    .18 * billions_of_numbers

gives a new array of numbers that contains the result of multiplying each number in `billions_of_numbers` by .18.  Arrays are not limited to numbers; we can also put all the words in a book into an array of strings.

Concretely, an array is a **collection of values of the same type**. 

## 1.1. Making arrays

First, let's learn how to manually input values into an array. This typically isn't how programs work. Normally, we create arrays by loading them from an external source, like a data file.

To create an array by hand, call the function `make_array`.  Each argument you pass to `make_array` will be in the array it returns.  Run this cell to see an example:

In [282]:
make_array(0.125, 4.75, -1.3)

array([ 0.125,  4.75 , -1.3  ])

Each value in an array (in the above case, the numbers 0.125, 4.75, and -1.3) is called an *element* of that array.

Arrays themselves are also values, just like numbers and strings.  That means you can assign them to names or use them as arguments to functions. For example, `len(<some_array>)` returns the number of elements in `some_array`.

**Question 1.1.1.** Make an array containing the numbers $\pi$, 1, -1, 0, and $e$, in that order.  Name it `interesting_numbers`.  

*Hint:* How have you found the values $\pi$ and $e$ earlier in this course?

<!--
BEGIN QUESTION
name: q111
-->

In [285]:
import math

interesting_numbers = make_array(math.pi, 1, -1, 0, math.e)
interesting_numbers

array([ 3.14159265,  1.        , -1.        ,  0.        ,  2.71828183])

**Question 1.1.2.** Make an array containing the five strings `"Hello"`, `","`, `" "`, `"world"`, and `"!"`.  (The third one is a single space inside quotes.)  Name it `hello_world_components`.

*Note:* If you evaluate `hello_world_components`, you'll notice some extra information in addition to its contents: `dtype='<U5'`.  That's just NumPy's extremely cryptic way of saying that the data types in the array are strings.

<!--
BEGIN QUESTION
name: q112
-->

In [287]:
hello_world_components = make_array("Hello", ",", " ", "world", "!")
hello_world_components

array(['Hello', ',', ' ', 'world', '!'],
      dtype='<U5')

###  `np.arange`
Arrays are provided by a package called [NumPy](http://www.numpy.org/) (pronounced "NUM-pie"). The package is called `numpy`, but it's standard to rename it `np` for brevity.  You can do that with:

    import numpy as np

Very often in data science, we want to work with many numbers that are evenly spaced within some range.  NumPy provides a special function for this called `arange`.  The line of code `np.arange(start, stop, step)` evaluates to an array with all the numbers starting at `start` and counting up by `step`, stopping **before** `stop` is reached.

Run the following cells to see some examples!

In [289]:
# This array starts at 1 and counts up by 2
# and then stops before 6
np.arange(1, 6, 2)

array([1, 3, 5])

In [290]:
# This array doesn't contain 9
# because np.arange stops *before* the stop value is reached
np.arange(4, 9, 1)

array([4, 5, 6, 7, 8])

**Question 1.1.3.** Create an array with the multiples of 34 from 0 up to (**and including**) 3434.  (So its elements are 0, 34, 68, 102, etc.)

<!--
BEGIN QUESTION
name: q113
-->

In [292]:
multiples_of_34 = np.arange(0, 3435, 34)
multiples_of_34

array([   0,   34,   68,  102,  136,  170,  204,  238,  272,  306,  340,
        374,  408,  442,  476,  510,  544,  578,  612,  646,  680,  714,
        748,  782,  816,  850,  884,  918,  952,  986, 1020, 1054, 1088,
       1122, 1156, 1190, 1224, 1258, 1292, 1326, 1360, 1394, 1428, 1462,
       1496, 1530, 1564, 1598, 1632, 1666, 1700, 1734, 1768, 1802, 1836,
       1870, 1904, 1938, 1972, 2006, 2040, 2074, 2108, 2142, 2176, 2210,
       2244, 2278, 2312, 2346, 2380, 2414, 2448, 2482, 2516, 2550, 2584,
       2618, 2652, 2686, 2720, 2754, 2788, 2822, 2856, 2890, 2924, 2958,
       2992, 3026, 3060, 3094, 3128, 3162, 3196, 3230, 3264, 3298, 3332,
       3366, 3400, 3434])

##### Temperature readings
NOAA (the US National Oceanic and Atmospheric Administration) operates weather stations that measure surface temperatures at different sites around the United States.  The hourly readings are [publicly available](http://www.ncdc.noaa.gov/qclcd/QCLCD?prior=N).

Suppose we download all the hourly data from the Raleigh-Durham International Airport site for the semester, from August 15, 2022 to December 9, 2022.  To analyze the data, we want to know when each reading was taken, but we find that the data do not include the timestamps of the readings (the time at which each one was taken).

However, we know the first reading was taken at the first instant of August 15th 2022 (midnight on August 15th) and each subsequent reading was taken exactly 1 hour after the last.

**Question 1.1.4.** Create an array of the *time, in seconds, since the start of the August 15th, and ending before the start of December 10th* at which each hourly reading was taken.  Name it `collection_times`.

*Hint 1:* How many days are in each month? There are 30 days in September, which is equivalent to ($30 \times 24$) hours or ($30 \times 24 \times 60 \times 60$) seconds.

<!--
BEGIN QUESTION
name: q114
-->

In [294]:
total_time_seconds = 10108800
collection_times = np.arange(0, total_time_seconds, 3600)
collection_times

array([       0,     3600,     7200, ..., 10098000, 10101600, 10105200])

## 1.2. Working with single elements of arrays ("indexing")
Let's work with a more interesting dataset.  The next cell creates an array called `NCpop` that includes estimated North Carolina populations in every year from 1900 to roughly the present. The estimates come from the [FRED Economic Data](https://fred.stlouisfed.org/series/NCPOP).


In [296]:
NCpop = Table.read_table("NCpop.csv").column("NCPOP")
NCpop

array([ 1897000,  1926000,  1956000,  1986000,  2017000,  2051000,
        2077000,  2105000,  2142000,  2174000,  2221000,  2276000,
        2313000,  2362000,  2421000,  2473000,  2513000,  2546000,
        2522000,  2535000,  2588000,  2651000,  2700000,  2761000,
        2830000,  2895000,  2959000,  3027000,  3082000,  3133000,
        3167000,  3184000,  3227000,  3268000,  3304000,  3323000,
        3346000,  3385000,  3440000,  3514000,  3574000,  3589000,
        3569000,  3654000,  3560000,  3533000,  3706000,  3769000,
        3837000,  3911000,  4068000,  4120000,  4109000,  4120000,
        4131000,  4242000,  4309000,  4368000,  4376000,  4458000,
        4573000,  4663000,  4707000,  4742000,  4802000,  4863000,
        4896000,  4952000,  5004000,  5031000,  5084411,  5203531,
        5301150,  5389852,  5470911,  5547188,  5607964,  5685607,
        5759492,  5823491,  5898980,  5956653,  6019101,  6077056,
        6164006,  6253954,  6321578,  6403700,  6480594,  6565

Here's how we get the first element of `NCpop`, which is the world population in the first year in the dataset, 1900.

In [298]:
NCpop.item(0)

1897000

The value of that expression is the number 1897000 (almost 2 million), because that's the first thing in the array `NCpop`.

Notice that we wrote `.item(0)`, not `.item(1)`, to get the first element.  This is a weird convention in computer science.  0 is called the *index* of the first item.  It's the number of elements that appear *before* that item.  So 3 is the index of the 4th item.

Here are some more examples.  In the examples, we've given names to the things we get out of `NCpop`.  Read and run each cell.

In [300]:
# The 13th element in the array is the population
# in 1912 (which is 1900 + 12).
nc_pop_1912 = NCpop.item(12)
nc_pop_1912

2313000

In [301]:
# The 66th element is the population in 1965.
nc_pop_1965 = NCpop.item(65)
nc_pop_1965

4863000

In [302]:
# The array has only 122 elements, so this doesn't work.
# (There's no element with 122 other elements before it.)
nc_pop_2022 = NCpop.item(122)
population_2022

IndexError: index 122 is out of bounds for axis 0 with size 122

Since `make_array` returns an array, we can call `.item(3)` on its output to get its 4th element, just like we "chained" together calls to the method `replace` earlier.

In [ ]:
make_array(-1, -3, 4, -2).item(3)

**Question 2.2.1.** Set `population_1979` to the North Carolina population in 1979, by getting the appropriate element from `NCpop` using `item`.

<!--
BEGIN QUESTION
name: q221
-->

In [ ]:
population_1979 = NCpop.item(79)
population_1979

## 1.3. Doing something to every element of an array
Arrays are primarily useful for doing the same operation many times, so we don't often have to use `.item` and work with single elements.

##### Logarithms
Here is one simple question we might ask about world population:

> How big was the population in *orders of magnitude* in each year?

Orders of magnitude quantify how big a number is by representing it as the power of another number (for example, representing 104 as $10^{2.017033}$). One way to do this is by using the logarithm function. The logarithm (base 10) of a number increases by 1 every time we multiply the number by 10. It's like a measure of how many decimal digits the number has, or how big it is in orders of magnitude.

We could try to answer our question like this, using the `log10` function from the `math` module and the `item` method you just saw:

In [ ]:
nc_pop_1900_magnitude = math.log10(NCpop.item(0))
nc_pop_1901_magnitude = math.log10(NCpop.item(1))
nc_pop_1902_magnitude = math.log10(NCpop.item(2))
nc_pop_1903_magnitude = math.log10(NCpop.item(3))
nc_pop_1903_magnitude = math.log10(NCpop.item(4))

But this is tedious and doesn't really take advantage of the fact that we are using a computer.

Instead, NumPy provides its own version of `log10` that takes the logarithm of each element of an array.  It takes a single array of numbers as its argument.  It returns an array of the same length, where the first element of the result is the logarithm of the first element of the argument, and so on.

**Question 1.3.1.** Use `np.log10` to compute the logarithms of the North Carolina population in every year.  Give the result (an array of 122 numbers) the name `NCpop_magnitudes`.  Your code should be very short.

<!--
BEGIN QUESTION
name: q131
-->

In [ ]:
NCpop_magnitudes = np.log10(NCpop)
NCpop_magnitudes

What you just did is called *elementwise* application of `np.log10`, since `np.log10` operates separately on each element of the array that it's called on. Here's a picture of what's going on:

<img src="lab03-array_logarithm.jpg">


The textbook's [section](https://www.inferentialthinking.com/chapters/05/1/Arrays)  on arrays has a useful list of NumPy functions that are designed to work elementwise, like `np.log10`.

##### Arithmetic
Arithmetic also works elementwise on arrays, meaning that if you perform an arithmetic operation (like subtraction, division, etc) on an array, Python will do the operation to every element of the array individually and return an array of all of the results. For example, you can divide all the population numbers by 1 million to get numbers in millions:

In [ ]:
NCpop_in_millions = NCpop / 1000000
NCpop_in_millions

You can do the same with addition, subtraction, multiplication, and exponentiation (`**`). For example, you can calculate a tip on several restaurant bills at once (in this case just 3):

In [ ]:
restaurant_bills = make_array(20.12, 39.90, 31.01)
print("Restaurant bills:\t", restaurant_bills)

# Array multiplication
tips = .2 * restaurant_bills
print("Tips:\t\t\t", tips)

<img src="lab03-array_multiplication.jpg">

**Question 1.3.2.** Suppose the total charge at a restaurant is the original bill plus the tip. If the tip is 20%, that means we can multiply the original bill by 1.2 to get the total charge.  Compute the total charge for each bill in `restaurant_bills`, and assign the resulting array to `total_charges`.

<!--
BEGIN QUESTION
name: q532
-->

In [ ]:
total_charges = 1.2 * restaurant_bills
total_charges

**Question 1.3.3.** The array `more_restaurant_bills_array` contains 100,000 bills!  Compute the total charge for each one.  How is your code different?

<!--
BEGIN QUESTION
name: q133
-->

In [ ]:
more_restaurant_bills_array = Table.read_table("more_restaurant_bills.csv").column("Bill")
more_total_charges = 1.2 * more_restaurant_bills_array
more_total_charges

The function `sum` takes a single array of numbers as its argument.  It returns the sum of all the numbers in that array (so it returns a single number, not an array).

**Question 1.3.4.** What was the sum of all the bills in `more_restaurant_bills_array`, *including tips*? Round your answer to the nearest cent.

<!--
BEGIN QUESTION
name: q134
-->

In [ ]:
sum_of_bills = sum(more_restaurant_bills_array)
sum_of_bills

## 2. Creating Tables

An array is useful for describing a single attribute of each element in a collection. For example, let's say our collection is all US States. Then an array could describe the land area of each state. 

Tables extend this idea by containing multiple arrays, each one describing a different attribute for every element of a collection. In this way, tables allow us to not only store data about many entities but to also contain several kinds of data about each entity.

For example, in the cell below we have two arrays. The first one, `NCpop`, was defined above in section 2.2 and contains the North Carolina population in each year. The second array, `years`, contains the years themselves. These elements are in order, so the year and the North Carolina population for that year have the same index in their corresponding arrays.

In [ ]:
# Just run this cell

years = np.arange(1900, 2021+1)
print("Population column:", NCpop)
print("Years column:", years)

Suppose we want to answer this question:

> In which year did the North Carolina's population cross 5 million?

You could technically answer this question by importing and viewing the full NCpop table that includes the years, or just from staring at the arrays and counting the position where the population first crossed 5 million. We won't do that since we want how to learn to do these things when those methods may not be available. 

The expression below:

- creates an empty table using the expression `Table()`,
- adds two columns by calling `with_columns` with four arguments,
- assigns the result to the name `population`, and finally
- evaluates `population` so that we can see the table.

The strings `"Year"` and `"Population"` are column labels that we have chosen. The names `NCpop` and `years` were assigned above to two arrays of the **same length**. The function `with_columns` takes in alternating strings (to represent column labels) and arrays (representing the data in those columns). The strings and arrays are separated by commas.

In [ ]:
population = Table().with_columns(
    "Population", NCpop,
    "Year", years
)
population

Now the data is combined into a single table! It's much easier to parse this data. If you need to know what the population was in 1959, for example, you can tell from a single glance.

## 3. More Table Operations!

Now that you've worked with arrays, let's add a few more methods to the list of table operations that you saw in Lab 2. Run the cell below

In [ ]:
# Returns a table of the amount of restaurant bills
more_restaurant_bills = Table.read_table("more_restaurant_bills.csv")
more_restaurant_bills

### `column`

`column` takes the column name of a table (in string format) as its argument and returns the values in that column as an **array**.  Run the cell below.

In [ ]:
# Returns an array of the amount of restaurant bills
more_restaurant_bills.column('Bill')

Note that both the array above and the table `more_restaurant_bills` only have data for one variable, but their structures are different. Many functions that we will use expect the data to be in either an array format or a table format, but can not handle both.

### `take`
The table method `take` takes as its argument an array of numbers.  Each number should be the index of a row in the table.  It returns a **new table** with only those rows. 

You'll usually want to use `take` in conjunction with `np.arange` to take the first few rows of a table.

In [ ]:
# Take first 100 amounts of restaurant bills
more_restaurant_bills.take(np.arange(0, 100, 1))

The next questions will give you practice with combining the operations you've learned in this lab and the previous one to answer questions about the `population` table. First, check out the `population` table from section 2.

In [ ]:
# Run this cell to display the population table.
population

**Question 3.1.** Compute the year when the North Carolina population first went above 5 million. Assign the year to `year_NCpop_crossed_5_million`. 
<!--
BEGIN QUESTION
name: q31
-->

In [308]:
NCpop.take(np.arange(50,70, 1))
year_NCpop_crossed_5_million = 1968
year_NCpop_crossed_5_million

1968

**Question 3.2.** Find the average yearly change in North Carolina's population for 1980's (years from 1980 and 1990 (inclusive)) and the average yearly change in North Carolina population for 2010's (years from 2010 and 2020 (inclusive)). You should round to the nearest whole number.

*Hint*: Think of the steps you need to do and try to put them in an order that makes sense.

*Hint*: In a previous assignment you used a function that calculated the differences between adjacent values in an array

<!--
BEGIN QUESTION
name: q42
-->

In [ ]:
between_1980_and_1990 = np.mean(np.diff(NCpop.take(np.arange(79,89, 1))))
between_2010_and_2020 = np.mean(np.diff(NCpop.take(np.arange(109,119, 1))))
print("Average yearly change in North Carolina's population for the 1980's:", between_1980_and_1990)
print("Average yearly change in North Carolina's population for the 2010's", between_2010_and_2020)

## 4. Visualizations

Tables are a powerful way of organizing and visualizing data. However, large tables of numbers can be difficult to interpret, no matter how organized they are. Sometimes it is much easier to interpret graphs than numbers. Next you will use some fundamental graphical methods of data analysis to view the data from tables in a different way.

**Question 4.1.** Line plots, sometimes known as line graphs, are among the most common visualizations. They are often used to study chronological trends and patterns. Construct a line plot using the `population` table to plot the North Carolina population over time. Plot `Year` on the horizontal axis and `Population` on the vertical axis.

In [ ]:
population.plot("Year")

Run the cell below to load the table `primary_results`. This table has the votes for each candidate or ballot choice in every contest held in North Carolina in the May 8, 2018 elections.

In [ ]:
primary_results = Table.read_table('primary_results.csv')
primary_results.show(5)

**Question 4.2.** Construct a table `OCBOE` containing only the rows for the `contest_name` of `ORANGE COUNTY BOARD OF EDUCATION` and containing only the columns of `choice` and `sum_total_votes`. The table should be sorted in decreasing order by `sum_total_votes`.

In [ ]:
OCBOE = primary_results.where("contest_name", "ORANGE COUNTY BOARD OF EDUCATION").sort('sum_total_votes', descending=True)
OCBOE

**Question 4.3.** Construct a barplot for the number of votes for each of the candidates in teh `OCBOE` table.

In [ ]:
OCBOE.barh('choice', 'sum_total_votes')

Run the cell below to load the `Local_Air_Quality` table. This dataset contains air quality data collected using a PurpleAir Dual Laser Air Quality Sensor located at the Chapel Hill Public Library, as well as data on other variables such as temperature in Fahrenheit.

In [ ]:
Local_Air_Quality = Table.read_table("Local_Air_Quality.csv")
Local_Air_Quality.show(5)

**Question 4.4.** Construct a scatterplot with the variable `Humidity` on the horizontal axis and `Pressure__mbar` on the vertical axis. Note that there are two underscores in the name `Pressure__mbar`

In [ ]:
Local_Air_Quality.scatter("Humidity", "Pressure__mbar", fit_line = True)

**Question 4.5.** Comment on the relationship between `Humidity` and `Pressure__mbar` shown in the plot from the previos question.

As Humidity increases in the local air quality, the pressure_mbar decreases in the local air quality.

# You're done with Lab 3! 
Save the Jupyter Notebook and submit it to Gradescope.